version: '3'

services:
  db:
    container_name: postgres_express
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lordran
      - POSTGRES_PASSWORD=lordran
      - POSTGRES_DB=mobiles_db
    ports:
      - 5433:5432

  pgadmin:
    depends_on:
      - db
    container_name: pgadmin_express
    image: dpage/pgadmin4:6.17
    environment:
      - PGADMIN_DEFAULT_EMAIL=lordran@lordran.dev
      - PGADMIN_DEFAULT_PASSWORD=lordranpass
    ports:
      - 80:80

volumes:
  pgdata: